export type textureInterface = {
    top?: string
    bottom?: string
    vert?: string
    "360"?: string
    stroke?: boolean
    disabled?: boolean
    name?: string
}
export default [{ "360": "worms", "stroke": false, "name": "Patriciella" },
    { "360": "paths", "stroke": false, "name": "Rudolfius" },
    { "360": "panter", "stroke": false, "name": "Pantera" },
    { "360": "panter", "stroke": true, "name": "Panterus" },
    { "360": "leafs", "stroke": false, "name": "Corpatrick" },
    { "360": "leafs", "stroke": true, "name": "Rubanus" },
    { "360": "giraffe", "stroke": false, "name": "Maartjilla" },
    { "360": "giraffe", "stroke": true, "name": "Erikellus" },
    { "360": "dots", "stroke": false, "name": "Jeroenimus" },
    { "360": "dots","stroke": true,"name": "Rachella" },
    { "360": "cow","stroke": false,"name": "Jonius" },
    { "360": "cow","stroke": true,"name": "Mauella" },
    { "360": "camo","stroke": false,"name": "Andrellus" },
    { "360": "camo","stroke": true,"name": "Pucketia" },
    { "top": "t1","bottom": "b1","stroke": false,"name": "Larsentius" },
    { "top": "t1","bottom": "b2","stroke": false,"name": "Jarinus" },
    { "top": "t1","bottom": "b2","stroke": true,"name": "Liekia" },
    { "top": "t1","bottom": "b3","stroke": false,"name": "Koosinus" },
    { "top": "t1","bottom": "b4","stroke": false,"name": "Koosentius" },
    { "top": "t1","bottom": "b5","stroke": false,"name": "Silkoos" },
    { "top": "t1","bottom": "b8","stroke": false,"name": "Loesina" },
    { "top": "t1","bottom": "b8","stroke": true,"name": "Loesissa" },
    { "top": "t1","stroke": false,"name": "Steefentius" },
    { "top": "t1","stroke": true,"name": "Aritonius" },
    { "top": "t2","bottom": "b1","stroke": false,"name": "Maartenor" },
    { "top": "t2","bottom": "b1","stroke": true,"name": "Valishanti" },
    { "top": "t2","bottom": "b2","stroke": false,"name": "Marcellus" },
    { "top": "t2","bottom": "b3","stroke": false,"name": "Marceltius" },
    { "top": "t2","bottom": "b4","stroke": false,"name": "Tessella" },
    { "top": "t2","bottom": "b5","stroke": false,"name": "Tesselius" },
    { "top": "t2","bottom": "b6","stroke": false,"name": "Flortessia" },
    { "top": "t2","bottom": "b7","stroke": false,"name": "Gabiella" },
    { "top": "t2","bottom": "b8","stroke": false,"name": "Wardus" },
    { "top": "t2","bottom": "b8","stroke": true,"name": "Maartentius" },
    { "top": "t2","stroke": false,"name": "Henkillus" },
    { "top": "t2","stroke": true,"name": "Silkim" },
    { "top": "t3","bottom": "b2","stroke": false,"name": "Kimona" },
    { "top": "t3","bottom": "b3","stroke": false,"name": "Amiella" },
    { "top": "t3","bottom": "b3","stroke": true,"name": "Jeffara" },
    { "top": "t3","bottom": "b4","stroke": false,"name": "Jeffator" },
    { "top": "t3","bottom": "b5","stroke": false,"name": "Seppator" },
    { "top": "t3","bottom": "b6","stroke": false,"name": "Rowissa" },
    { "top": "t3","bottom": "b8","stroke": false,"name": "Lisetia" },
    { "top": "t3","stroke": false,"name": "Lisara" },
    { "top": "t3","stroke": true,"name": "Rodrigorius" },
    { "top": "t4","bottom": "b1","stroke": false,"name": "Corellus" },
    { "top": "t4","bottom": "b2","stroke": false,"name": "Robillus" },
    { "top": "t4","bottom": "b2","stroke": true,"name": "Matentius" },
    { "top": "t4","bottom": "b5","stroke": false,"name": "Michielus" },
    { "top": "t4","bottom": "b6","stroke": false,"name": "Selmaia" },
    { "top": "t4","bottom": "b6","stroke": true,"name": "Maroskar" },
    { "top": "t4","bottom": "b7","stroke": false,"name": "Renellus" },
    { "top": "t4","bottom": "b8","stroke": false,"name": "Litorius" },
    { "top": "t4","stroke": false,"name": "Ludona" },
    { "top": "t4","stroke": true,"name": "Martinia" },
    { "top": "t5","bottom": "b1","stroke": false,"name": "Basius" },
    { "top": "t5","bottom": "b1","stroke": true,"name": "Aniekellia" },
    { "top": "t5","bottom": "b2","stroke": false,"name": "Florius" },
    { "top": "t5","bottom": "b2","stroke": true,"name": "Ematia" },
    { "top": "t5","bottom": "b3","stroke": false,"name": "Harliator" },
    { "top": "t5","bottom": "b3","stroke": true,"name": "Tommentius" },
    { "top": "t5","bottom": "b4","stroke": false,"name": "Mitchellus" },
    { "top": "t5","bottom": "b5","stroke": false,"name": "Jolandia" },
    { "top": "t5","bottom": "b5","stroke": true,"name": "Aurianus" },
    { "top": "t5","bottom": "b6","stroke": false,"name": "Valius" },
    { "top": "t5","bottom": "b7","stroke": false,"name": "Lucicus" },
    { "top": "t5","bottom": "b7","stroke": true,"name": "Marcicus" },
    { "top": "t5","bottom": "b8","stroke": false,"name": "Coricus" },
    { "top": "t5","stroke": false,"name": "Silentius" },
    { "top": "t5","stroke": true,"name": "Florator" },
    { "top": "t6","bottom": "b1","stroke": false,"name": "Serus" },
    { "top": "t6","bottom": "b2","stroke": false,"name": "Amylita" },
    { "top": "t6","bottom": "b2","stroke": true,"name": "Valitia" },
    { "top": "t6","bottom": "b3","stroke": false,"name": "Luciella" },
    { "top": "t6","bottom": "b5","stroke": false,"name": "Marciella" },
    { "top": "t6","bottom": "b5","stroke": true,"name": "Corissa" },
    { "top": "t6","bottom": "b6","stroke": false,"name": "Siletia" },
    { "top": "t6","bottom": "b7","stroke": false,"name": "Florella" },
    { "top": "t6","stroke": false,"name": "Serella" },
    { "top": "t7","bottom": "b1","stroke": false,"name": "Aurium" },
    { "top": "t7","bottom": "b1","stroke": true,"name": "Valius" },
    { "top": "t7","bottom": "b2","stroke": false,"name": "Luciora" },
    { "top": "t7","bottom": "b3","stroke": false,"name": "Maron" },
    { "top": "t7","bottom": "b3","stroke": true,"name": "Cores" },
    { "top": "t7","bottom": "b4","stroke": false,"name": "Siluxio" },
    { "top": "t7","bottom": "b4","stroke": true,"name": "Florar" },
    { "top": "t7","bottom": "b5","stroke": false,"name": "Seron" },
    { "top": "t7","bottom": "b6","stroke": true,"name": "Valitricia" },
    { "top": "t7","bottom": "b7","stroke": true,"name": "Rudinus" },
    { "top": "t7","bottom": "b8","stroke": false,"name": "Ianellus" },
    { "top": "t7","stroke": false,"name": "Lucianux" },
    { "top": "t7","stroke": true,"name": "Ianuxia" },
    { "top": "t8","bottom": "b1","stroke": false,"name": "Erikus" },
    { "top": "t8","bottom": "b1","stroke": true,"name": "Erikia" },
    { "top": "t8","bottom": "b2","stroke": true,"name": "Lucioentje" },
    { "top": "t8","bottom": "b3","stroke": true,"name": "Rachelus" },
    { "top": "t8","bottom": "b5","stroke": false,"name": "Rubentius" },
    { "top": "t8","bottom": "b5","stroke": true,"name": "Rubentia" },
    { "top": "t8","bottom": "b6","stroke": true,"name": "Merella" },
    { "top": "t8","bottom": "b7","stroke": false,"name": "Rubenium" },
    { "top": "t8","bottom": "b7","stroke": true,"name": "Jeffus" },
    { "top": "t8","bottom": "b8","stroke": false,"name": "Novakoos" },
    { "top": "t8","stroke": false,"name": "Jariella" },
    { "top": "t8","stroke": true,"name": "Janentius" },
    { "top": "t9","bottom": "b1","stroke": false,"name": "Janus" },
    { "top": "t9","bottom": "b1","stroke": true,"name": "Rowiella" },
    { "top": "t9","bottom": "b2","stroke": false,"name": "Vilarly" },
    { "top": "t9","bottom": "b2","stroke": true,"name": "Maroes" },
    { "top": "t9","bottom": "b3","stroke": false,"name": "Maritchel" },
    { "top": "t9","bottom": "b3","stroke": true,"name": "Tommissa" },
    { "top": "t9","bottom": "b4","stroke": false,"name": "Liekus" },
    { "top": "t9","bottom": "b4","stroke": true,"name": "Marakim" },
    { "top": "t9","bottom": "b5","stroke": false,"name": "Ludora" },
    { "top": "t9","bottom": "b5","stroke": true,"name": "Kevius" },
    { "top": "t9","bottom": "b6","stroke": false,"name": "Kevia" },
    { "top": "t9","bottom": "b6","stroke": true,"name": "Xenia" },
    { "top": "t9","bottom": "b7","stroke": true,"name": "Xeniellus" },
    { "top": "t9","bottom": "b8","stroke": false,"name": "Puckster" },
    { "top": "t9","bottom": "b8","stroke": true,"name": "Puckorius" },
    { "top": "t9","stroke": false,"name": "Jolandarius" },
    { "top": "t9","stroke": true,"name": "Patranus" },
    { "top": "t10","bottom": "b1","stroke": false,"name": "Celagaby" },
    { "top": "t10","bottom": "b2","stroke": false,"name": "Teresa" },
    { "top": "t10","bottom": "b2","stroke": true,"name": "Gabriella" },
    { "top": "t10","bottom": "b3","stroke": true,"name": "Willemorius" },
    { "top": "t10","bottom": "b5","stroke": false,"name": "Willemton" },
    { "top": "t10","bottom": "b7","stroke": true,"name": "Aritor" },
    { "top": "t10","bottom": "b8","stroke": true,"name": "Arina" },
    { "top": "t10","stroke": false,"name": "Mienora" },
    { "top": "t10","stroke": true,"name": "Minia" },
    { "bottom": "b1","stroke": false,"name": "Maxius" },
    { "bottom": "b1","stroke": true,"name": "Maxia" },
    { "bottom": "b2","stroke": false,"name": "Minius" },
    { "bottom": "b2","stroke": true,"name": "Cassandra" },
    { "bottom": "b3","stroke": false,"name": "Juliella" },
    { "bottom": "b4","stroke": false,"name": "Julissa" },
    { "bottom": "b4","stroke": true,"name": "Julianus" },
    { "bottom": "b5","stroke": false,"name": "Patrickorius" },
    { "bottom": "b5","stroke": true,"name": "Patranus" },
    { "bottom": "b6","stroke": false,"name": "Loesella" },
    { "bottom": "b6","stroke": true,"name": "Marcelicus" },
    { "bottom": "b7","stroke": false,"name": "Larsia" },
    { "bottom": "b7","stroke": true,"name": "Larsissa" },
    { "bottom": "b8","stroke": false,"name": "Narcissicus" },
    { "bottom": "b8","stroke": true,"name": "Rowiorius" },
    { "vert": "v1","stroke": false,"name": "Seppster" },
    { "vert": "v1","stroke": true,"name": "Seppentius" },
    { "vert": "v2","stroke": false,"name": "Eriki" },
    { "vert": "v2","stroke": true,"name": "Robinia" },
    { "vert": "v3","stroke": false,"name": "Robentius" },
    { "vert": "v3","stroke": true,"name": "Tomillus" },
    { "vert": "v4","stroke": false,"name": "Timia" },
    { "vert": "v5","stroke": false,"name": "Timora" },
    { "vert": "v5","stroke": true,"name": "Timentius" },
    { "vert": "v6","stroke": false,"name": "Vionia" },
    { "vert": "v6","stroke": true,"name": "Silossia" },
    { "vert": "polkadots","stroke": false,"name": "Polkadotius" },
    { "vert": "polkadots","stroke": true,"name": "Polkadotia" },
    { "360": "mandala","stroke": true,"name": "Mandalorius" },
    { "360": "mandala2","stroke": true,"name": "Mandalina" },
    { "360": "mandala3","stroke": false,"name": "Mandora" },
    { "360": "mandala4","stroke": true,"name": "Mandentius" },
    { "360": "mandala4","stroke": false,"name": "Mandella" },
    { "top": "t11","stroke": true,"name": "Amyus" },
    { "top": "t11","stroke": false,"name": "Sjefficus" },
    { "top": "t11","bottom":"b2","stroke": false,"name": "Yanickus" },
    { "top": "t11","bottom":"b3","stroke": false,"name": "Liekius" },
    { "top": "t11","bottom":"b3","stroke": false,"name": "Jeffentius" },
    { "top": "t11","bottom":"b4","stroke": false,"name": "Patricus" },
    { "top": "t11","bottom":"b6","stroke": false,"name": "Rachellus" },
    { "top": "t11","bottom":"b7","stroke": false,"name": "Steefanus" },
    { "top": "t11","bottom":"b8","stroke": false,"name": "Stevanus" },
    { "top": "t11","bottom":"b9","stroke": false,"name": "Stevanio" },
    { "top": "t11","bottom":"b10","stroke": false,"name": "Vaniono" },
    { "top": "t11","bottom":"b13","stroke": false,"name": "Iejun" },
    { "top": "t11","bottom":"b14","stroke": false,"name": "Iejunes" },
    { "top": "t11","bottom":"b16","stroke": false,"name": "Ianus" },
    { "top": "t12","stroke": false,"name": "Aritionius" },
    { "top": "t12","bottom":"b2","stroke": false,"name": "Wessicus" },
    { "top": "t12","bottom":"b3","stroke": false,"name": "Weslinus" },
    { "top": "t12","bottom":"b8","stroke": false,"name": "Andrius" },
    { "top": "t12","bottom":"b10","stroke": false,"name": "Maurellus" },
    { "top": "t12","bottom":"b10","stroke": true,"name": "Rudius" },
    { "top": "t12","bottom":"b13","stroke": true,"name": "Rubenticus" },
    { "top": "t12","bottom":"b13","stroke": false,"name": "Michellia" },
    { "top": "t12","bottom":"b14","stroke": false,"name": "Yulia" },
    { "top": "t12","bottom":"b16","stroke": false,"name": "Minicus" },
    { "top": "t12","bottom":"b16","stroke": true,"name": "Meniscus" },
    { "top": "t12","bottom":"b17","stroke": false,"name": "Koosella" },
    { "top": "t12","bottom":"b17","stroke": true,"name": "Iania" },
    { "bottom":"b9","stroke": true,"name": "Sepporia" },
    { "bottom":"b9","stroke": true,"name": "Sepia" },
    { "top": "t1","bottom":"b9","stroke": true,"name": "Sepina" },
    { "top": "t2","bottom":"b9","stroke": true,"name": "Sepetia" },
    { "top": "t3","bottom":"b9","stroke": true,"name": "kinderbijslag" },
    { "top": "t4","bottom":"b9","stroke": true,"name": "Rowiella" },
    { "top": "t5","bottom":"b9","stroke": true,"name": "Rowissa" },
    { "top": "t6","bottom":"b9","stroke": true,"name": "Mariella" },
    { "top": "t7","bottom":"b9","stroke": true,"name": "Maria" },
    { "top": "t8","bottom":"b9","stroke": true,"name": "Mara" },
    { "top": "t9","bottom":"b9","stroke": true,"name": "Jefissa" },
    { "top": "t10","bottom":"b9","stroke": true,"name": "Ruditor" },
    { "bottom":"b10","stroke": true,"name": "Paticicux" },
    { "bottom":"b10","stroke": false,"name": "Patrictor" },
    { "top": "t1","bottom":"b10","stroke": false,"name": "Gabia" },
    { "top": "t2","bottom":"b10","stroke": false,"name": "Gabetia" },
    { "top": "t3","bottom":"b10","stroke": false,"name": "Pucktorius" },
    { "top": "t4","bottom":"b10","stroke": false,"name": "Aritonicus" },
    { "top": "t5","bottom":"b10","stroke": false,"name": "Kosiko" },
    { "top": "t6","bottom":"b10","stroke": false,"name": "Jolandicus" },
    { "top": "t7","bottom":"b10","stroke": false,"name": "Jolandux" },
    { "top": "t8","bottom":"b10","stroke": false,"name": "Jolandix" },
    { "top": "t9","bottom":"b10","stroke": false,"name": "Jolandor" },
    { "top": "t10","bottom":"b10","stroke": false,"name": "Willium" },
    { "top": "t11","bottom":"b10","stroke": false,"name": "Sandrix" },
    { "top": "t12","bottom":"b10","stroke": false,"name": "Sandraetta" },

    { "bottom":"b11","stroke": true,"name": "Jeronium" },
    { "bottom":"b11","stroke": false,"name": "Jeronux" },
    { "top": "t1","bottom":"b11","stroke": false,"name": "Jeronix" },
    { "top": "t2","bottom":"b11","stroke": false,"name": "Jeronia" },
    { "top": "t3","bottom":"b11","stroke": false,"name": "Maartor" },
    { "top": "t4","bottom":"b11","stroke": false,"name": "Maartjix" },
    { "top": "t5","bottom":"b11","stroke": false,"name": "Kimoria" },
    { "top": "t6","bottom":"b11","stroke": false,"name": "Kimissa" },
    { "top": "t7","bottom":"b11","stroke": false,"name": "Kimia" },
    { "top": "t8","bottom":"b11","stroke": false,"name": "Loesoria" },
    { "top": "t9","bottom":"b11","stroke": false,"name": "Loesiux" },
    { "top": "t10","bottom":"b11","stroke": false,"name": "Loesius" },
    { "bottom":"b12","stroke": true,"name": "Kosix" },
    { "bottom":"b12","stroke": false,"name": "Victorius" },
    { "top": "t1","bottom":"b12","stroke": false,"name": "Victorina" },
    { "top": "t2","bottom":"b12","stroke": false,"name": "Vitus" },
    { "top": "t3","bottom":"b12","stroke": false,"name": "Jasperium" },
    { "top": "t4","bottom":"b12","stroke": false,"name": "Zouhariux" },
    { "top": "t5","bottom":"b12","stroke": false,"name": "Annetor" },
    { "top": "t6","bottom":"b12","stroke": false,"name": "Michieletta" },
    { "top": "t7","bottom":"b12","stroke": false,"name": "Michielium" },
    { "top": "t8","bottom":"b12","stroke": false,"name": "Jonika" },
    { "top": "t9","bottom":"b12","stroke": false,"name": "Tessium" },
    { "top": "t10","bottom":"b12","stroke": false,"name": "Tessiux" },
    
    { "bottom":"b13","stroke": false,"name": "Tessox" },
    { "top": "t1","bottom":"b13","stroke": false,"name": "Jeffox" },
    { "top": "t4","bottom":"b13","stroke": false,"name": "Kimox" },
    { "top": "t5","bottom":"b13","stroke": false,"name": "Septor" },
    { "top": "t6","bottom":"b13","stroke": false,"name": "Ralfius" },
    { "top": "t7","bottom":"b13","stroke": false,"name": "Ralphius" },
    { "top": "t8","bottom":"b13","stroke": false,"name": "Ralpia" },
    { "top": "t8","bottom":"b13","stroke": true,"name": "Emiliux" },
    { "top": "t9","bottom":"b13","stroke": false,"name": "Suzanium" },
    { "top": "t12","bottom":"b13","stroke": false,"name": "Suzania" },

    { "bottom":"b14","stroke": true,"name": "Suzanicus" },
    { "top": "t1","bottom":"b13","stroke": false,"name": "Mathildia" },
    { "top": "t1","bottom":"b13","stroke": true,"name": "Guusjentius" },
    { "top": "t3","bottom":"b13","stroke": true,"name": "Maros" },
    { "top": "t4","bottom":"b13","stroke": false,"name": "Varel" },
    { "top": "t6","bottom":"b13","stroke": false,"name": "Ianel" },
    { "top": "t7","bottom":"b13","stroke": false,"name": "Kimen" },
    { "top": "t8","bottom":"b13","stroke": false,"name": "Puckietta" },
    { "top": "t8","bottom":"b13","stroke": true,"name": "Romelia" },
    { "top": "t9","bottom":"b13","stroke": false,"name": "Robinium" },
    { "top": "t10","bottom":"b13","stroke": false,"name": "Robinux" },
    { "top": "t10","bottom":"b13","stroke": false,"name": "Corux" },

    { "bottom":"b14","stroke": true,"name": "Corator" },
    { "bottom":"b14","stroke": false,"name": "Coriella" },
    { "top": "t1","bottom":"b14","stroke": false,"name": "Corium" },
    { "top": "t2","bottom":"b14","stroke": false,"name": "Ronix" },
    { "top": "t2","bottom":"b14","stroke": true,"name": "Ronux" },
    { "top": "t3","bottom":"b14","stroke": false,"name": "Hildux" },
    { "top": "t4","bottom":"b14","stroke": false,"name": "Hildator" },
    { "top": "t5","bottom":"b14","stroke": false,"name": "Anster" },
    { "top": "t6","bottom":"b14","stroke": false,"name": "Anikon" },
    { "top": "t7","bottom":"b14","stroke": false,"name": "Janium" },
    { "top": "t8","bottom":"b14","stroke": false,"name": "Sjefium" },
    { "top": "t9","bottom":"b14","stroke": false,"name": "Jeffium" },
    { "top": "t10","bottom":"b14","stroke": false,"name": "Jeffux" },
    { "top": "t11","bottom":"b14","stroke": true,"name": "Martinium" },

    { "bottom":"b15","stroke": true,"name": "Willenium" },
    { "bottom":"b15","stroke": false,"name": "Gertia" },
    { "top": "t1","bottom":"b15","stroke": false,"name": "Gerticon" },
    { "top": "t2","bottom":"b15","stroke": true,"name": "Henketta" },
    { "top": "t4","bottom":"b15","stroke": false,"name": "Henkux" },
    { "top": "t5","bottom":"b15","stroke": true,"name": "Loesetta" },
    { "top": "t6","bottom":"b15","stroke": false,"name": "Marcellium" },
    { "top": "t7","bottom":"b15","stroke": false,"name": "Marcilim" },
    { "top": "t7","bottom":"b15","stroke": true,"name": "Dannycus" },
    { "top": "t8","bottom":"b15","stroke": false,"name": "Dannycux" },
    { "top": "t9","bottom":"b15","stroke": true,"name": "Danior" },
    { "top": "t9","bottom":"b15","stroke": false,"name": "Danium" },
    { "top": "t10","bottom":"b15","stroke": false,"name": "Danitor" },

    { "bottom":"b16","stroke": false,"name": "Wardux" },
    { "top": "t2","bottom":"b16","stroke": false,"name": "Wardix" },
    { "top": "t3","bottom":"b16","stroke": false,"name": "Stefanicus" },
    { "top": "t4","bottom":"b16","stroke": false,"name": "Stephanicus" },
    { "top": "t5","bottom":"b16","stroke": true,"name": "Stefanium" },
    { "top": "t6","bottom":"b16","stroke": false,"name": "Stefaniux" },
    { "top": "t7","bottom":"b16","stroke": false,"name": "Jaellix" },
    { "top": "t8","bottom":"b16","stroke": true,"name": "Jallium" },
    { "top": "t8","bottom":"b16","stroke": false,"name": "Ardax" },
    { "top": "t9","bottom":"b16","stroke": false,"name": "Ardux" },
    { "top": "t10","bottom":"b16","stroke": false,"name": "Aidarux" },

    { "bottom":"b17","stroke": true,"name": "Aidator" },
    { "bottom":"b17","stroke": false,"name": "Nitorius" },
    { "top": "t2","bottom":"b17","stroke": false,"name": "Nitorium" },
    { "top": "t3","bottom":"b17","stroke": false,"name": "Skyton" },
    { "top": "t4","bottom":"b17","stroke": false,"name": "Skyux" },
    { "top": "t5","bottom":"b17","stroke": true,"name": "Sylvianux" },
    { "top": "t6","bottom":"b17","stroke": false,"name": "Silvania" },
    { "top": "t7","bottom":"b17","stroke": false,"name": "Kyanux" },
    { "top": "t7","bottom":"b17","stroke": true,"name": "Brayina" },
    { "top": "t9","bottom":"b17","stroke": false,"name": "Joeya" },
    { "top": "t9","bottom":"b17","stroke": false,"name": "Jennia" },
    { "top": "t10","bottom":"b17","stroke": true,"name": "Shantiux" },
    
    { "bottom":"b18","stroke": true,"name": "Mauritsius" },
    { "bottom":"b18","stroke": false,"name": "Ahmetor" },
    { "top": "t2","bottom":"b18","stroke": false,"name": "Alix" },
    { "top": "t2","bottom":"b18","stroke": true,"name": "Alexius" },
    { "top": "t3","bottom":"b18","stroke": false,"name": "Jamis" },
    { "top": "t4","bottom":"b18","stroke": false,"name": "Jamixius" },
    { "top": "t6","bottom":"b18","stroke": false,"name": "Jamyxa" },
    { "top": "t6","bottom":"b18","stroke": true,"name": "Jefixia" },
    { "top": "t8","bottom":"b18","stroke": false,"name": "Brendarus" },
    { "top": "t9","bottom":"b18","stroke": false,"name": "Leroyia" },
    { "top": "t10","bottom":"b18","stroke": false,"name": "Irisia" },
    { "top": "t12","bottom":"b18","stroke": false,"name": "Irissicux" },
    { "top": "t12","bottom":"b18","stroke": false,"name": "Lissarius" },
    
    { "bottom":"b19","stroke": true,"name": "Lisia" },
    { "bottom":"b19","stroke": false,"name": "Stijnia" },
    { "top": "t2","bottom":"b19","stroke": false,"name": "Fladux" },
    { "top": "t2","bottom":"b19","stroke": true,"name": "Flidux" },
    { "top": "t4","bottom":"b19","stroke": false,"name": "Vanoxia" },
    { "top": "t6","bottom":"b19","stroke": true,"name": "Roxicus" },
    { "top": "t6","bottom":"b19","stroke": false,"name": "Soricia" },
    { "top": "t7","bottom":"b19","stroke": false,"name": "Lexorius" },
    { "top": "t8","bottom":"b19","stroke": false,"name": "Nitox" },
    { "top": "t10","bottom":"b19","stroke": false,"name": "Janilliux" },
    

    { "vert": "v7","stroke": false,"name": "Glitchix" },
    { "vert": "v7", "top": "t12", "stroke": false,"name": "Glitchix" },
    { "vert": "v7", "bottom": "b1", "stroke": false,"name": "Glitchor" },
    { "vert": "v7", "bottom": "b2", "stroke": false,"name": "Glitchifus" },
    { "vert": "v7", "bottom": "b5", "stroke": false,"name": "Glitchia" },
    
    { "vert": "v8","stroke": false,"name": "Puppytooth" },
    { "vert": "v8","stroke": true,"name": "Puppytoothix" },
    { "vert": "v8","bottom": "b1", "stroke": false,"name": "Puppix" },
    { "vert": "v8","bottom": "b9", "stroke": false,"name": "Puppytor" },
    { "vert": "v8","bottom": "b10", "stroke": false,"name": "Puppytoothsia" },
    { "vert": "v8","bottom": "b18", "stroke": false,"name": "Puppytotihum" },
    { "vert": "v8","bottom": "b19", "stroke": false,"name": "Puppiella" },

    
    { "vert": "v9","stroke": false,"name": "Streporius" },
    { "vert": "v9","stroke": true,"name": "Stripia" },
    { "vert": "v9","bottom": "b1", "stroke": false,"name": "Stripux" },
    { "vert": "v9","bottom": "b9", "stroke": false,"name": "Striptor" },
    { "vert": "v9","bottom": "b10", "stroke": false,"name": "Stripiux" },
    { "vert": "v9","bottom": "b13", "stroke": false,"name": "Strepia" },
    { "vert": "v9","bottom": "b17", "stroke": false,"name": "Stripesis" },
    { "vert": "v9","bottom": "b18", "stroke": false,"name": "Striporia" },

    { "vert": "v10","top": "t11", "stroke": false,"name": "Ariux" },
    { "vert": "v10","top": "t12", "stroke": false,"name": "Aria" },
    { "vert": "v10","bottom": "b1", "stroke": false,"name": "Arius" },
    { "vert": "v10","bottom": "b17", "stroke": false,"name": "Lucariux" },
    { "vert": "v10","bottom": "b18", "stroke": false,"name": "Lucasia" },
    { "vert": "v10","bottom": "b19", "stroke": false,"name": "Petoriux" },

    { "vert": "v11", "stroke": false,"name": "Borix" },
    { "vert": "v11","bottom":"b1", "stroke": false,"name": "Vladiux" },
    { "vert": "v11","bottom":"b10", "stroke": true,"name": "Petriella" },
    { "vert": "v11","bottom":"b10", "stroke": true,"name": "Petranux" },
    { "vert": "v11","bottom":"b11", "stroke": false,"name": "Petracia" },
    { "vert": "v11","bottom":"b11", "stroke": true,"name": "Hugorius" },
    { "vert": "v11","bottom":"b17", "stroke": false,"name": "Pepynia" },
    { "vert": "v11","bottom":"b12", "stroke": true,"name": "Pepynux" },
    { "vert": "v11","bottom":"b14", "stroke": false,"name": "Pepyria" },
    { "vert": "v11","bottom":"b15", "stroke": false,"name": "Liania" },
    
    { "vert": "v12", "bottom": "b1", "stroke": false,"name": "Anleicia" },
    { "vert": "v12", "bottom": "b1", "stroke": true,"name": "Fredericus" },
    { "vert": "v12", "bottom": "b2", "stroke": false,"name": "Fredoria" },
    { "vert": "v12", "bottom": "b3", "stroke": false,"name": "Karstonia" },
    { "vert": "v12", "bottom": "b4", "stroke": false,"name": "Jurios" },
    { "vert": "v12", "bottom": "b5", "stroke": false,"name": "Jerrynimos" },
    { "vert": "v12", "bottom": "b5", "stroke": true,"name": "Matthiux" },
    { "vert": "v12", "bottom": "b6", "stroke": false,"name": "Fredorius" },
    { "vert": "v12", "bottom": "b7", "stroke": false,"name": "Jentor" },
    { "vert": "v12", "bottom": "b7", "stroke": true,"name": "Brambux" },
    { "vert": "v12", "bottom": "b8", "stroke": false,"name": "Bramtor" },
    { "vert": "v12", "bottom": "b9", "stroke": true,"name": "Jessux" },
    { "vert": "v12", "bottom": "b10", "stroke": true,"name": "Jessoria" },
    { "vert": "v12", "bottom": "b13", "stroke": false,"name": "Jessellia" },
    { "vert": "v12", "bottom": "b13", "stroke": true,"name": "Kaylia" },
    { "vert": "v12", "bottom": "b14", "stroke": false,"name": "Kayloria" },
    { "vert": "v12", "bottom": "b15", "stroke": false,"name": "Kavix" },
    { "vert": "v12", "bottom": "b15", "stroke": true,"name": "Kavorius" },
    { "vert": "v12", "bottom": "b17", "stroke": false,"name": "Kevix" },
    { "vert": "v12", "bottom": "b18", "stroke": false,"name": "Kevius" },
    { "vert": "v12", "bottom": "b18", "stroke": true,"name": "Keviux" },
    { "vert": "v12", "bottom": "b18", "stroke": true,"name": "Mennorius" },
    { "vert": "v12", "top": "t2", "stroke": true,"name": "Riannux" },
    { "vert": "v12", "top": "t3", "stroke": false,"name": "Stonius" },
    { "vert": "v12", "top": "t3", "stroke": true,"name": "Stoniux" },
    { "vert": "v12", "top": "t5", "stroke": true,"name": "Tommius" },
    { "vert": "v12", "top": "t10", "stroke": true,"name": "Tommytor" },
    { "vert": "v12", "top": "t11", "stroke": false,"name": "Rodricux" },
    { "vert": "v12", "top": "t12", "stroke": false,"name": "Suex" },
    

    
] as Array < textureInterface >